<?php

namespace OpenWebAddict\CaptchetatBundle\Service;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

interface CaptchetatServiceInterface 
{
    /**
     * Fetch the Captchetat API access token.
     *
     * @return string The access token generated by the CaptchEtat API.
     */
    public function fetchApiToken(): string;

    /**
     * Returns the Captchetat API access token.
     *
     * @return string The access token generated by the CaptchEtat API.
     */
    public function getApiToken(): string;

    /**
     * Returns the CaptchEtat API status.
     *
     * @param string $token
     *   CaptchEtat API access token.
     *
     * @return mixed
     *   Returns the CaptchEtat status info or FALSE on failure.
    */
    public function healthCheck(string $token): mixed;

    /**
     * Checks if the CaptchEtat service is up.
     *
     * @param string $token
     *   CaptchEtat API access token.
     *
     * @return bool
     *   Returns true if the CaptchEtat service is up, false otherwise.
     */
    public function isServiceUp(string $token): bool;

    /**
     * Returns the CaptchEtat API response.
     *
     * @param string $token
     *   CaptchEtat API access token.
     * @param Request $request
     *   The current http request.
     *
     * @return Response
     *   Returns the HTTP Response for the CaptchEtat API element.
     */
    public function getCaptcha(string $token, Request $request): Response;

    /**
     * Validates the user submission.
     *
     * @param string $captcha_uuid
     *   The captcha unique ID.
     * @param string $user_entered_captcha_code
     *   The user entered captcha code.
     * @param string $token
     *   CaptchEtat API access token.
     *
     * @return bool
     *   TRUE if validation successful, FALSE otherwise.
    */
    public function validateCaptcha(string $captcha_uuid, string $user_entered_captcha_code, string $token): bool;

}
