<?php

namespace OpenWebAddict\CaptchetatBundle\Service;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

interface CaptchetatServiceInterface 
{
    /**
     * Fetch the Captchetat API access token.
     *
     * @return string The access token generated by the CaptchEtat API.
     */
    public function fetchApiToken(): string;

    /**
     * Returns the Captchetat API access token.
     *
     * @return string The access token generated by the CaptchEtat API.
     */
    public function getApiToken(): string;

    /**
     * Returns the CaptchEtat API status.
     *
     * @param string $token
     *   CaptchEtat API access token.
     *
     * @return mixed
     *   Returns the CaptchEtat status info or FALSE on failure.
    */
    public function healthCheck(string $token): mixed;

    /**
     * Checks if the CaptchEtat service is up.
     *
     * @param string $token
     *   CaptchEtat API access token.
     *
     * @return bool
     *   Returns true if the CaptchEtat service is up, false otherwise.
     */
    public function isServiceUp(string $token): bool;

    /**
     * Returns the CaptchEtat API URL.
     * 
     * @param string $captchaObjectType
     *   CaptchEtat API object type ( image | sound )
     * 
     * @param string $captchaType
     *      Captcha name to get
     * 
     * @return string
     *   Returns the CaptchEtat  .
     */
    public function getCaptcha(
        string $captchaObjectType = 'image', 
        string $captchaType = 'numerique6_7CaptchaFR', 
        ?string $captchaId = null
    ): string;

    /**
     * Validates the user submission.
     *
     * @param string $captchaUuid
     *   The captcha unique ID.
     * @param string $userEnteredCode
     *   The user entered captcha code.
     *
     * @return bool
     *   TRUE if validation successful, FALSE otherwise.
    */
    public function validateCaptcha(string $captchaUuid, string $userEnteredCode): bool;
}
