# config/services.yaml
services:
  OpenWebAddict\CaptchetatBundle\Service\CaptchetatService:
    arguments:
      $sandbox: '%monbundle.sandbox%'
      $public_key: '%monbundle.public_key%'
      $private_key: '%monbundle.private_key%'

